### ISSUE TITLE
Modifying the locating path for opencl.h

### ISSUE THREAD

**Issue by YifangZhang** [zhengxwen/HIBAG.gpu#2]
Dear HIBAG.gpu Admins,

I have encountered a challenge in order to install your package onto a supercomputer. Here is the log:

```
/usr/apps/general/spack/sw/linux-rhel8-zen/gcc-8.5.0/gcc-11.3.0-cwx43q6qt46zl5olgckurx67xtg4nuyd/bin/g++ -std=gnu++14 -I"/usr/apps/general/spack/sw/linux-rhel8-zen/gcc-11.3.0/r-4.2.0-2liuw4vmic27cmqhyyt6jmvwbezn6mlx/rlib/R/include" -DNDEBUG  -I'/usr/apps/general/spack/sw/linux-rhel8-zen/gcc-11.3.0/r-4.2.0-2liuw4vmic27cmqhyyt6jmvwbezn6mlx/rlib/R/library/HIBAG/include' -I/usr/local/include   -fpic  -g -O2  -c LibHLA_gpu.cpp -o LibHLA_gpu.o
In file included from LibHLA_gpu.cpp:37:
LibOpenCL.h:28:17: fatal error: CL/opencl.h: No such file or directory
   28 | #       include <CL/opencl.h>
      |                 ^~~~~~~~~~~~~
compilation terminated.
make: *** [/usr/apps/general/spack/sw/linux-rhel8-zen/gcc-11.3.0/r-4.2.0-2liuw4vmic27cmqhyyt6jmvwbezn6mlx/rlib/R/etc/Makeconf:177: LibHLA_gpu.o] Error 1
```

We have had an opencl.h located at `$CUDA_HOME/include/CL/opencl.h`, is there a way I can redirect the path into the correct location?

Best,

**Comment by zhengxwen** [comment]
Sorry, have not checked HIBAG.gpu for a while.
Try setting `C_INCLUDE_PATH` (for C header files) or `CPLUS_INCLUDE_PATH` (for C++ header files) environment variables to include `$CUDA_HOME/include`.
You might also need to set an appropriate `$LD_LIBRARY_PATH`.

**Comment by zhengxwen** [comment]
If you use the new commit (HIBAG.gpu_0.99.1): https://github.com/zhengxwen/HIBAG.gpu/commit/67cfdadb416ee43df70128e5f45bbfbb38262555

You can use the environment variables 'OCL_LIB' and 'OCL_INC' to the appropriate location.

**Comment by YifangZhang** [comment]
I think your previous solution already solved the problem, and thank you so much!
